
version: "3.8"

services:

  #  PostgreSQL
  postgres-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: spring-petclinic-mine

  #  App
  spring-petclinic-mine:
    depends_on:
      - postgres-db
    image: spring-petclinic-mine-image
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:postgresql://postgres-db:5432/spring-petclinic-mine",
          "spring.datasource.username" : "postgres",
          "spring.datasource.password" : "root",
          "spring.datasource.initialization-mode" : "always",
          "spring.datasource.continue-on-error" : "true",
          "spring.datasource.max-wait" : "30000",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.jpa.show-sql" : "true",          
          "spring.jpa.open-in-view" : "false",
          "spring.messages.basename" : "messages/messages"                                   
      }'