# Postgres Deployment
apiVersion : apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: spring-petclinic-mine-postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      project: spring-petclinic-mine-postgres
  template:
    metadata:
      labels:
        project: spring-petclinic-mine-postgres
    spec:
      containers:
        - name : postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "spring-petclinic-mine"
          # readinessProbe:
            # exec:
              # command:
                # - "pg_isready"
                # - "-U"
                # - "postgres"
                # - "-d"
                # - "spring-petclinic-mine"
            # initialDelaySeconds: 15
            # periodSeconds: 10
            # timeoutSeconds: 5
            # successThreshold: 1
            # failureThreshold: 3

---
# Postgres Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
     env  : dev
     owner: IvanGorbunov
spec:
  selector:
    project: spring-petclinic-mine-postgres
  ports:
    - name      : postgres-listener
      protocol  : TCP
      port      : 5432
      targetPort: 5432
  #type: CLusterIP